<?php
	$b_table="carpool_content,carpool_order,carpool_user,mag_api_column,mag_api_method,mag_setting";
	$tb[carpool_content]=1;
$tb[carpool_order]=1;
$tb[carpool_user]=1;
$tb[mag_api_column]=1;
$tb[mag_api_method]=1;
$tb[mag_setting]=1;

	$b_baktype=0;
	$b_filesize=300;
	$b_bakline=500;
	$b_autoauf=1;
	$b_dbname="pcxcx";
	$b_stru=1;
	$b_strufour=0;
	$b_dbchar="auto";
	$b_beover=0;
	$b_insertf="replace";
	$b_autofield=",,";
	$b_bakdatatype=0;
	?>